nickreq typescript rewrite
NewCircuit/nickreq pull request #1
Opened 2021-07-01 09:40 UTC by Aman25ta

@DankDumpster

2021-07-03 09:53 UTC, DankDumpster requested changes
Forgot to mention, I recommend using eslint with the airbnb preset. 

Certain rules like `no-console` can be turned off ofc

2021-07-03 09:53 UTC, DankDumpster commented on config.json
> +		"host": "",
Could you possibly use .yml files for config?

2021-07-03 09:53 UTC, DankDumpster commented on package.json
> +    "@newcircuit/logging.js": "git+https://github.com/NewCircuit/logging.js.git",
You can remove this for now

2021-07-03 09:53 UTC, DankDumpster commented on src/commands/nickreq/nickreq.ts
> +		if (args.length < 1) {
Its possible to provide args in the constructor, example:

```ts
      args: [
        {
          key: 'nickname',
          prompt: 'What is the nickname you want to request?',
          type: 'string',
          infinite: true,
        },
      ], 
```

More info here: https://discordjs.guide/commando/args.html#string-arguments

2021-07-03 09:53 UTC, DankDumpster commented on src/commands/nickreq/nickreq.ts
> +		await channel.send({
Nit: This indentation is inconsistent

2021-07-03 09:53 UTC, DankDumpster commented on src/db.ts
> +// .finally(() => pool.end())
Could you possibly make an sql file? For example in

migrations/init.sql

2021-07-03 09:53 UTC, DankDumpster commented on src/db.ts
> +module.exports.reject = reject;
Nit: No EOF

2021-07-03 09:53 UTC, DankDumpster commented on tsconfig.json
> +    "target": "es6",
Note: You can target es2020, if you require certain features

2021-07-03 09:53 UTC, DankDumpster commented on src/index.ts
> +.registerCommandsIn(path.join(__dirname,"commands"));
Nit: Indentation

2021-07-03 09:53 UTC, DankDumpster commented on src/db.ts
> +async function check(userid) {
Possibly better to use static methods here?

2021-07-03 09:53 UTC, DankDumpster commented on src/commands/nickreq/nickreq.ts
> +let db = require("../../db.js");
Could you possibly use import syntax?

2021-07-03 09:53 UTC, DankDumpster commented on src/commands/nickreq/nickreq.ts
> +module.exports = class nickReq extends commando.Command {
You can do 

```ts
export default class nickReq extends commando.Command
```

2021-07-03 11:40 UTC, Aman25ta commented
Will do

As for the string args, as im taking everything after, what would be the
advantage of using it, if any?

On Sat, 3 Jul 2021 at 12:53 PM Matthew ***@***.***> wrote:

> *@DankDumpster* requested changes on this pull request.
>
> Forgot to mention, I recommend using eslint with the airbnb preset.
>
> Certain rules like no-console can be turned off ofc
> ------------------------------
>
> In config.json
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344293>:
>
> > @@ -0,0 +1,14 @@
> +{
> +	"token": "",
> +	"botId": "",
> +	"channelid": "",
> +	"color": "0x20d84e",
> +	"ownerid": "",
> +	"postgres": {
> +		"username": "",
> +		"password": "",
> +		"host": "",
>
> Could you possibly use .yml files for config?
> ------------------------------
>
> In package.json
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344300>:
>
> >    "dependencies": {
> -    "discord.js": "^12.5.1",
> -    "discord.js-commando": "github:discordjs/commando",
> -    "dotenv": "^8.2.0"
> +    ***@***.***/logging.js": "git+https://github.com/NewCircuit/logging.js.git",
>
> You can remove this for now
> ------------------------------
>
> In src/commands/nickreq/nickreq.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344465>:
>
> > +
> +	constructor(client) {
> +		super(client , {
> +			name: 'request',
> +			group: 'nickreq',
> +			memberName: 'request',
> +			description: 'Main Nickname Request commands',
> +			argstype: 'single'
> +		})
> +	}
> +	async run(message, args) {
> +		if (message.guild == null) return
> +		if (args.length > 32) {
> +			return await message.reply("The nickname must be less than 32 characters");
> +		}
> +		if (args.length < 1) {
>
> Its possible to provide args in the constructor, example:
>
>       args: [
>         {
>           key: 'nickname',
>           prompt: 'What is the nickname you want to request?',
>           type: 'string',
>           infinite: true,
>         },
>       ],
>
> More info here:
> https://discordjs.guide/commando/args.html#string-arguments
> ------------------------------
>
> In src/commands/nickreq/nickreq.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344549>:
>
> > +				iconURL: message.author.avatarURL()
> +			},
> +			footer: {text: message.author.id}
> +		})
> +		let button1 = new MessageButton()
> +				.setLabel("Accept")
> +		    .setStyle("green")
> +		    .setID("Accepted");
> +		let button2 = new MessageButton()
> +				.setLabel("Reject")
> +		    .setStyle("red")
> +		    .setID("Rejected");
> +		let row = new MessageActionRow()
> +		  .addComponent(button1)
> +		  .addComponent(button2);
> +		await channel.send({
>
> Nit: This indentation is inconsistent
> ------------------------------
>
> In src/db.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344596>:
>
> > +	host: config.postgres.host,
> +	port: config.postgres.port,
> +	database: config.postgres.dbname
> +})
> +
> +
> +// pool.connect()
> +// .then(() => console.log("Connected"))
> +// .then(() => pool.query("DROP TABLE nickreq"))
> +// .then(() => pool.query(`CREATE TABLE nickreq (
> +// 	user_id VARCHAR ( 50 ) NOT NULL,
> +// 	nick VARCHAR ( 50 ) NOT NULL,
> +// 	state BOOLEAN
> +// );`))
> +// .catch(err => console.error(err))
> +// .finally(() => pool.end())
>
> Could you possibly make an sql file? For example in
>
> migrations/init.sql
> ------------------------------
>
> In src/db.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344665>:
>
> > +	userid = userid.toString()
> +	const results = await pool.query("UPDATE nickreq SET state=$1 WHERE user_id = $2 AND state IS NULL",[1 , userid]);
> +	return results.rows
> +}
> +
> +
> +async function reject(userid) {
> +	userid = userid.toString()
> +	const results = await pool.query("UPDATE nickreq SET state=$1 WHERE user_id = $2 AND state IS NULL",[0 , userid]);
> +	return results.rows
> +}
> +
> +module.exports.check = check;
> +module.exports.insert = insert;
> +module.exports.accept = accept;
> +module.exports.reject = reject;
>
> Nit: No EOF
> ------------------------------
>
> In tsconfig.json
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344724>:
>
> > -    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */
> -
> -    /* Source Map Options */
> -    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
> -    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
> -    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
> -    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */
> -
> -    /* Experimental Options */
> -    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
> -    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
> -
> -    /* Advanced Options */
> -    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
> -    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
> +    "target": "es6",
>
> Note: You can target es2020, if you require certain features
> ------------------------------
>
> In src/index.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344768>:
>
> >
> -client.login(process.env.DISCORD_TOKEN);
> +
> +
> +client.registry.registerGroup('nickreq','nickreq commands')
> +.registerDefaults()
> +.registerCommandsIn(path.join(__dirname,"commands"));
>
> Nit: Indentation
> ------------------------------
>
> In src/db.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344820>:
>
> > +	database: config.postgres.dbname
> +})
> +
> +
> +// pool.connect()
> +// .then(() => console.log("Connected"))
> +// .then(() => pool.query("DROP TABLE nickreq"))
> +// .then(() => pool.query(`CREATE TABLE nickreq (
> +// 	user_id VARCHAR ( 50 ) NOT NULL,
> +// 	nick VARCHAR ( 50 ) NOT NULL,
> +// 	state BOOLEAN
> +// );`))
> +// .catch(err => console.error(err))
> +// .finally(() => pool.end())
> +
> +async function check(userid) {
>
> Possibly better to use static methods here?
> ------------------------------
>
> In src/commands/nickreq/nickreq.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344915>:
>
> > @@ -0,0 +1,71 @@
> +const commando = require("discord.js-commando");
> +const discord = require("discord.js");
> +const { MessageButton, MessageActionRow } = require('discord-buttons');
> +let config = require('../../../config.json');
> +let db = require("../../db.js");
>
> Could you possibly use import syntax?
> ------------------------------
>
> In src/commands/nickreq/nickreq.ts
> <https://github.com/NewCircuit/nickreq/pull/1#discussion_r663344930>:
>
> > @@ -0,0 +1,71 @@
> +const commando = require("discord.js-commando");
> +const discord = require("discord.js");
> +const { MessageButton, MessageActionRow } = require('discord-buttons');
> +let config = require('../../../config.json');
> +let db = require("../../db.js");
> +
> +module.exports = class nickReq extends commando.Command {
>
> You can do
>
> export default class nickReq extends commando.Command
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NewCircuit/nickreq/pull/1#pullrequestreview-698581696>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALYPCF3KCAPPDNORRI2K743TV3MY5ANCNFSM47UEGT3A>
> .
>

2021-07-03 11:52 UTC, DankDumpster commented
Yes there would be, as its handled by discord.js commando. So it shows up in the help, also that is accomplished by the 
`infinite: true`

2021-07-08 12:18 UTC, Aman25ta commented
@DankDumpster , updated

2021-07-09 11:11 UTC, DankDumpster requested changes

2021-07-09 11:11 UTC, DankDumpster commented on migrations/init.sql
> +OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "mysqldump": executable file not found in $PATH: unknown
Looks like something went wrong here?

2021-07-09 11:11 UTC, DankDumpster commented on src/commands/nickreq/nickreq.ts
> +const commando = require('discord.js-commando');
Sorry, I mean that preferably you can use `import` syntax and only require if you have no other choice (e.g. the discord-buttons library)

2021-07-09 11:11 UTC, DankDumpster commented on src/commands/nickreq/nickreq.ts
> +    const button2 = new MessageButton()
Nit: Spacing

2021-07-09 11:11 UTC, DankDumpster commented on src/db.ts
> +// .finally(() => pool.end())
Looks like this wasn't updated correctly, could you take another look at it?

2021-07-09 11:11 UTC, DankDumpster commented on src/index.ts
> +  });
Nit: Spacing

2021-07-09 11:11 UTC, DankDumpster commented
@Aman25ta some small nits

2021-07-09 12:08 UTC, Aman25ta commented on migrations/init.sql
> +OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "mysqldump": executable file not found in $PATH: unknown
Weird, ill make another one

2021-07-11 11:25 UTC, DankDumpster requested changes
Looks like something went wrong with your migration again, everything looks good except that. Take a look at https://github.com/NewCircuit/suggestions/blob/master/pg.sql as example

2021-07-11 11:25 UTC, DankDumpster commented on src/db.ts
> +export default class Db {
NIT: Change to `DB`

2021-07-11 11:25 UTC, DankDumpster commented on package.json
> -  "license": "ISC",
Could you add a GPLV3 license?

2021-07-11 12:31 UTC, Aman25ta commented
@DankDumpster fixed the sql

2021-07-11 12:35 UTC, DankDumpster requested changes
Almost there, looks like you forgot to do `git add` on the new sql file tho

2021-07-11 12:35 UTC, DankDumpster commented on package.json
> +  "license": "GPLV3"
Oh didn't mean it literally, create a LICENSE file more info here:

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

2021-07-11 12:35 UTC, DankDumpster commented on src/db.ts
> +// .finally(() => pool.end())
This can be removed now :smile:

2021-07-11 12:41 UTC, Aman25ta commented
> Almost there, looks like you forgot to do `git add` on the new sql file tho

i can see the new file in the repo though :thinking:

2021-07-11 12:42 UTC, DankDumpster commented
Yeah you're right, was looking at the wrong thing :sweat_smile:

2021-07-12 20:58 UTC, DankDumpster approved these changes
LGTM, thanks!

2021-07-12 20:58 UTC, merged